---
- name: Install jq on Ubuntu EC2 instance
  hosts: all
  become: yes
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install jq
      apt:
        name: jq
        state: present
